from __future__ import annotations

from collections.abc import Sequence

from nicegui import ui

from simulator.environment import Environment
from simulator.view.audio import (
    cue_gains,
    cue_jitters,
    cue_repeats,
    cue_spreads,
    cue_urls,
)


class SoundBoard(ui.element, component="sound_board.js"):  # pyright: ignore[reportGeneralTypeIssues, reportCallIssue]
    """Play named sound cues in the browser."""

    def __init__(
        self,
        environment: Environment | None = None,
        *,
        volume: float = 1.0,
        muted: bool = False,
    ) -> None:
        super().__init__()
        self._props["sounds"] = cue_urls(environment)
        self._props["gains"] = cue_gains(environment)
        self._props["jitters"] = cue_jitters(environment)
        self._props["repeats"] = cue_repeats(environment)
        self._props["spreads"] = cue_spreads(environment)
        self._props["volume"] = volume
        self._props["muted"] = muted

    def play(self, cue: str) -> None:
        self.run_method("play", cue)

    def play_all(self, cues: Sequence[str]) -> None:
        """Play all cues generated by one simulation step."""
        if not cues:
            return
        self.run_method("playAll", list(cues))

    def set_muted(self, muted: bool) -> None:
        if muted == self._props["muted"]:
            return
        self._props["muted"] = muted
        self.update()
